### ISSUE TITLE
Strange LwM2M registration response.

### ISSUE THREAD

**Issue by FRDavid** [telefonicaid/lwm2m-node-lib#104]
**Original issue from the lightweight-iotagent project moved to this project**

Hello,

Note: This issue only appears in the grunt tests carried out by lightweigh-iotagent, not in the lwm2m-node-lib. Since the problem must be solved in lwm2m-node-lib, the issue has been opened in the lwm2m-node-lib project.

We have detected that the process of register a device is not carried out correctly due to the appearance of strange messages. They could appear also in other cases also. These messages are interspersed in the communications and produces problems since they are using the MID corresponding to the real response.

Seems libcoap is not waiting long enough for lightweight-iotagent and lwm2m-node-lib to send the response and we didn't find a way to disable this auto-response from libcoap.

This image shows the strange message using the correct MID for an "Empty response" generated automatically by libcoap, then the correct response using a different MID, so the correct response can not be correctly processed by the device.

![avoidfastresponse1](https://cloud.githubusercontent.com/assets/8007584/20344259/52849b98-abf2-11e6-9d61-d8afad33f57c.png)

A way to solve this issue is introduce the parameter "piggybackReplyMs" in the coap server creation, this is done in the lwm2m-node-lib library.

```
serverInfo.server = libcoap.createServer({
type: config.serverProtocol,
proxy: true,
piggybackReplyMs: 500
});
```

The piggybackReplyMs default value for libcoap library is 50ms and it seems too short for the processing time carried out by the lightweight-iotagent/lwm2m-node-lib set so I increased this value to 500 to ensure at least basic cases, but this should be evaluated in a future in other conditions such as overloaded.

Next image shows the communication after introduce this option. Now is clean from strange messages.

![avoidfastresponse2](https://cloud.githubusercontent.com/assets/8007584/20344555/86b4164a-abf3-11e6-8d6a-ef40ad5b56c3.png)

Tests are passed correctly in both lwm2m-node-lib and lightweight-iot agent.

BR,
David

**Comment by davidfdezros** [comment]
Hi again,

Confirmed, problem is related with the use of the node-coap library and the solution resides on modifications in lwm2m-node-lib library and/or node-coap.

I'm not completely sure about the node-coap library behaviour but seems the library will send an auto-response if no response is sent before a certain period. This period is set during the coap-server configuration with the piggybackReplyMs option (default is 50ms).

   ` serverInfo.server = libcoap.createServer({`
        `type: config.serverProtocol,`
        `proxy: true,`
       `piggybackReplyMs: 1500`
    `});`

If the user callback takes too much time, this auto-response is sent. This case happens on the lightweight-iotagent project when the IoT Agent communicates to the context broker.

I also tried with 0 value in piggybackReplyMs to disable this auto-response but does not work. 

Additionally, the line

`req._packet.messageId = res._packet.messageId`

 is required on the 'endRegistration' function in order to match the MID between the petition and the response.

![screen-registration-iotagent](https://cloud.githubusercontent.com/assets/8007584/16836355/74d79a02-49bd-11e6-9579-050f33d9f27c.png)

Test results are the same with and without these modifications, but a project developer with knowledge about the complete functionality (ack management in the project) must evaluate the impact of this change over other petitions such as read, write, observers, ...

Test results (without mongoDB):

  67 passing (7s)
  24 pending
  2 failing

These changes can be checked in: https://github.com/HOP-Ubiquitous/lwm2m-node-lib/commits/issue/registration

**Comment by FRDavid** [comment]
Since this issue was already solved and merged. I will close this issue.

**Comment by fgalan** [comment]
The fix is not mentioned in https://github.com/telefonicaid/lwm2m-node-lib/blob/develop/CHANGES_NEXT_RELEASE. Maybe it should be.

**Comment by FRDavid** [comment]
Should be, so @fgalan check the PR #119 recently added
